spring:
  config:
    activate:
      on-profile: dev

app:
  features:
    users-legacy:
      ui-enabled: ${APP_FEATURES_USERS_LEGACY_UI_ENABLED:true}
      read-enabled: ${APP_FEATURES_USERS_LEGACY_READ_ENABLED:true}
      write-enabled: ${APP_FEATURES_USERS_LEGACY_WRITE_ENABLED:true}
